In [2]:
import scaper
import pathlib
import numpy as np

In [3]:
BASE_PATH = pathlib.Path(".")

In [8]:
BASE_PATH = pathlib.Path(".")
data_path = BASE_PATH.joinpath("data")
fg_folder_path = data_path.joinpath("foreground")
bg_folder_path = data_path.joinpath("background")

assert fg_folder_path.exists()
assert bg_folder_path.exists()

In [21]:
# Settings
seed = 42
soundscape_duration = 5
ref_db = -60

In [22]:
sc = scaper.Scaper(
    soundscape_duration, 
    fg_folder_path,
    bg_folder_path
)

sc.ref_db = ref_db

In [23]:
sc.add_background(
    label = ("const", "park"),
    source_file = ("choose", []),
    source_time = ("const", 0)
)

'''
The distribution tuples currently supported by scaper are:

('const', value): a constant, given by value.
('choose', list): uniformly sample from a finite set of values given by list.
('uniform', min, max): sample from a uniform distribution between min and max.
('normal', mean, std): sample from a normal distribution with mean mean and standard deviation std.
('truncnorm', mean, std, min, max): sample from a truncated normal distribution with mean mean and standard deviation std, limited to values between min and max.

Special cases: 
the label and source_file parameters in sc.add_background() 
(and as we’ll see later sc.add_event() as well) must be specified using either 
the const or choose distribution tuples. When using choose, these two parameters 
(and only these) can also accept a special version of the choose tuple in the form ('choose', []),
i.e. with an empty list. In this case, scaper will use the file structure in the 
foreground and background folders to automatically populate the list with all valid labels 
(in the case of the label parameter) and all valid filenames (in the case of the source_file parameter).
'''
print("")

In [24]:
sc.add_event(label=('const', 'siren'),
             source_file=('choose', []),
             source_time=('const', 0),
             event_time=('uniform', 0, 9),
             event_duration=('truncnorm', 3, 1, 0.5, 5),
             snr=('normal', 10, 3),
             pitch_shift=('uniform', -2, 2), #set to none if not wanted
             time_stretch=('uniform', 0.8, 1.2)) #set to none if not wanted

In [25]:
for _ in range(2):
    sc.add_event(label=('choose', []),
                 source_file=('choose', []),
                 source_time=('const', 0),
                 event_time=('uniform', 0, 9),
                 event_duration=('truncnorm', 3, 1, 0.5, 5),
                 snr=('normal', 10, 3),
                 pitch_shift=None,
                 time_stretch=None)

In [26]:
audiofile = 'soundscape.wav'
jamsfile = 'soundscape.jams'
txtfile = 'soundscape.txt'
sc.generate(audiofile, jamsfile,
            allow_repeated_label=True,
            allow_repeated_source=True,
            reverb=0.1,
            disable_sox_warnings=True,
            no_audio=False,
            txt_path=txtfile)

/home/lux_t1/.conda/envs/endomic/lib/python3.8/site-packages/scaper/core.py:1563: ScaperWarning: siren event time (6.91) is too great given stretched event duration (4.76) and soundscape duration (5.00), changed to 0.24.
  warnings.warn(
/home/lux_t1/.conda/envs/endomic/lib/python3.8/site-packages/scaper/core.py:1439: ScaperWarning: human_voice event duration (3.21) is greater that source duration (1.54), changing to 1.54
  warnings.warn(
/home/lux_t1/.conda/envs/endomic/lib/python3.8/site-packages/scaper/core.py:1551: ScaperWarning: human_voice event time (5.27) is too great given event duration (1.54) and soundscape duration (5.00), changed to 3.46.
  warnings.warn(
/home/lux_t1/.conda/envs/endomic/lib/python3.8/site-packages/scaper/core.py:1439: ScaperWarning: car_horn event duration (4.41) is greater that source duration (0.69), changing to 0.69
  warnings.warn(
/home/lux_t1/.conda/envs/endomic/lib/python3.8/site-packages/scaper/core.py:1551: ScaperWarning: car_horn event time (5.5

(array([[0.00314349],
        [0.00353038],
        [0.0025444 ],
        ...,
        [0.00207778],
        [0.00196982],
        [0.00201653]]),
 <JAMS(file_metadata=<FileMetadata(...)>,
       annotations=[1 annotation],
       sandbox=<Sandbox(...)>)>,
 [[0.23615888546558672, 5.0, 'siren'],
  [3.4604308390022673, 5.0, 'human_voice'],
  [4.31249433106576, 5.0, 'car_horn']],
 [array([[0.00314351],
         [0.00353035],
         [0.00254442],
         ...,
         [0.00183243],
         [0.00167409],
         [0.00168479]]),
  array([[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]),
  array([[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]),
  array([[ 0.00000000e+00],
         [ 0.00000000e+00],
         [ 0.00000000e+00],
         ...,
         [-4.02957464e-09],
         [-1.00740008e-09],
         [ 0.00000000e+00]])])